// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0KaNJgEvP26fKykTRUdNh_rr_UId7QA',
    appId: '1:571926423373:web:8c704963de2c9ce32c3904',
    messagingSenderId: '571926423373',
    projectId: 'bukatrip-c5234',
    authDomain: 'bukatrip-c5234.firebaseapp.com',
    storageBucket: 'bukatrip-c5234.appspot.com',
    measurementId: 'G-TDLW27NGKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMV_xEilKszvqLOrKGasrNCrlCD73JXzM',
    appId: '1:571926423373:android:89dff14a480635b02c3904',
    messagingSenderId: '571926423373',
    projectId: 'bukatrip-c5234',
    storageBucket: 'bukatrip-c5234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJLtTae-cNmJQRZ7dmAPgnmSZ59cu_czs',
    appId: '1:571926423373:ios:b637fc25fd696adf2c3904',
    messagingSenderId: '571926423373',
    projectId: 'bukatrip-c5234',
    storageBucket: 'bukatrip-c5234.appspot.com',
    iosClientId: '571926423373-h33rd90n9gtljb0tuhglrkskl54611q5.apps.googleusercontent.com',
    iosBundleId: 'personal.robzimpulse.bukatrip.ios.bukatrip',
  );
}
